# Use an official Python runtime as a parent image
FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Make port 80 available to the world outside this container
EXPOSE 80

# Define environment variable
ENV DB_PATH=./chroma_db

# Set the maintainer label
LABEL maintainer="bo wang <wangbostc@gmail.com>"
LABEL version="0.0.1"

# Run app.py when the container launches
CMD ["python", "src/app.py"]
